export { Persik } from './Persik';
export { Home } from './Home';
export { Registration } from './Registration';
export { Charcard } from './Charсard';
export { Game } from './Game';
export { Revards } from './Revards';
export { Ld } from './Ld';
export { Abilities } from './Abilities';
export { Cyborgs } from './Cyborgs'
